IHC: Ensure IHC compiles out cleanly
"Eats, Shoots & Leaves" - if CONFIG_USE_IHC was not enabled, the
build would fail with the error

./include/hss_debug.h:87:32: error: expected expression before ')' token
          sbi_printf(__VA_ARGS__); \
                                ^
This was due to a trailing comma separator after macro arguments